name: Build & Deploy vod/xvod/x/all JSON

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: "0 2 * * *"   # 每天凌晨 2 点自动运行
  push:
    branches: [ main ]

jobs:
  build-vod:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build vod.json, xvod.json, x.json and all.json
        run: |
          mkdir -p docs
          # 生成 vod.json 和 xvod.json（直接用 vod.ts）
          bun run vod.ts docs/vod.json docs/xvod.json

          # 生成 x.json（用 kitty.config.x.ts）
          cp kitty.config.x.ts kitty.config.ts
          bunx kitty-parse -o docs/x.json

          # 合并成 all.json
          jq -s 'add' docs/vod.json docs/xvod.json docs/x.json > docs/all.json

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
