name: Smart Sync, Build & Deploy Kitty JSON

on:
  schedule:
    - cron: "0 2 * * *"   # 每天凌晨 2 点自动同步
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sync-build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Smart sync from d1y/kitty (exclude workflows, keep kitty.config.* and docs)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if ! git remote | grep -q upstream; then
            git remote add upstream https://github.com/d1y/kitty.git
          fi
          git fetch upstream

          for file in $(git ls-tree -r --name-only upstream/main); do
            # 跳过 workflows、所有 kitty.config.* 文件、docs 文件夹
            if [[ "$file" == .github/workflows/* ]] || [[ "$file" == kitty.config.* ]] || [[ "$file" == docs/* ]]; then
              echo "Skip $file"
              continue
            fi

            # 如果本地有修改，先备份
            if [[ -f "$file" ]] && ! git diff --quiet HEAD -- "$file"; then
              ts=$(date +%Y%m%d%H%M%S)
              backup="${file}_local_${ts}"
              mkdir -p "$(dirname "$backup")"
              mv "$file" "$backup"
              echo "Backed up local change: $file -> $backup"
            fi

            git checkout upstream/main -- "$file"
          done

          git add .
          git commit -m "smart sync: exclude workflows, keep kitty.config.* and docs, backup local changes" || true
          git push origin HEAD:main

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build JSON files
        run: |
          mkdir -p docs

          # 生成 x.json
          cp kitty.config.x.ts kitty.config.ts
          bunx kitty-parse -o docs/x.json

          # 生成 vod.json
          cp kitty.config.vod.ts kitty.config.ts
          bunx kitty-parse -o docs/vod.json

          # 生成 xvod.json
          cp kitty.config.xvod.ts kitty.config.ts
          bunx kitty-parse -o docs/xvod.json

          # 合并成 all.json
          jq -s 'add' docs/x.json docs/vod.json docs/xvod.json > docs/all.json

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
