name: Auto Build JSON on Repo Change

on:
  push:
    paths:
      - 'vod.ts'
      - 'x18/**.ts'
      - 'kitty.config.*.ts'
      - '.github/workflows/**'
      - 'docs/**'   # docs 目录变化也触发
  workflow_dispatch:

jobs:
  auto-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 保留完整历史，避免覆盖其他分支

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build vod.json, xvod.json, x.json and all.json
        run: |
          mkdir -p docs
          # 生成 vod.json 和 xvod.json（直接用 vod.ts）
          bun run vod.ts docs/vod.json docs/xvod.json

          # 生成 x.json（用 kitty.config.x.ts）
          cp kitty.config.x.ts kitty.config.ts
          bunx kitty-parse -o docs/x.json

          # 合并成 all.json
          jq -s 'add' docs/vod.json docs/xvod.json docs/x.json > docs/all.json

      - name: Keep CNAME if exists
        run: |
          if [ -f CNAME ]; then
            cp CNAME docs/CNAME
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
          keep_files: true   # 保留已有文件，不清空
